# Generated by Django 5.2.6 on 2025-09-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountActivationToken',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
